runtime: python37

env_variables:
  MYSQL_UNIX_SOCKET: "/cloudsql/roomah-attempt-1:asia-southeast2:roomah-user"
  MYSQL_USER: "roomah-user"
  MYSQL_PASSWORD: "roomah"
  MYSQL_DB: "roomah"
  MYSQL_CURSORCLASS: "DictCursor"
  MYSQL_HOST: "10.11.208.3"

vpc_access_connector:
  name: "projects/roomah-attempt-1/locations/asia-southeast2/connectors/connect-to-sql"
